### ISSUE TITLE
mediaisfullscreen attribute has buggy behaviour

### ISSUE THREAD

**Issue by mskorsur** [muxinc/media-chrome#710] opened 2023-08-02 14:18 UTC
Hello,

I've noticed that `mediaisfullscreen` attribute from media-fullscreen-button has inconsistent, buggy behaviour. When the page containing the video is first loaded, the attribute is already set on media-controller even though the video hasn't played and is not in fullscreen. Upon entering/exiting fullscreen mode, the attribute is working properly. Observed on latest version of media-chrome library. 

Can you please provide some guidance if this could be an issue with some sort of setup or if this is a bug reproducible on your end as well? Thanks!

**Comment by cjpillsbury** [comment] 2023-08-07 14:55
Hey @mskorsur could you give us some more information on this behavior?
- What version of Media Chrome are you using?
- What browser(s) are you using when this issue occurs?
- Can you provide a minimal reproducible example, e.g. on a codesandbox, public github repo, or similar?

Just an fyi, there were a few known issues with fullscreen that came up during our v1.0 initiative that should be resolved in the latest version of Media Chrome. Also, if this is happening on mobile, make sure you're using the `playsinline` attribute (See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attributes). Thanks!

**Comment by cjpillsbury** [comment] 2023-08-14 14:05
Closing due to inactivity. Happy to re-open if conversation picks back up.

**Closed by cjpillsbury** 2023-08-14 14:05 UTC
Labels: bug
