### ISSUE TITLE
What is the correct import for React?

### ISSUE THREAD

**Issue by simonhrogers** [muxinc/media-chrome#680] opened 2023-07-05 15:09 UTC
Hello,

For some reason in my next.js project, importing from `media-chrome/dist/react` as per the docs does not work, but the following does, despite being flagged as incorrect by typescript:

```
import {
  MediaController,
  MediaControlBar,
  MediaTimeRange,
  MediaTimeDisplay,
  MediaVolumeRange,
  MediaPlayButton,
  MediaMuteButton,
} from 'media-chrome/react'
```

Why does this work and the doc-specified import path not, and which should I be doing? 

Thanks!

Simon

**Comment by heff** [comment] 2023-07-06 23:27
Good question. @cjpillsbury did something break here?

**Comment by HermanBilous** [comment] 2023-07-07 09:21
I was playing with tsconfig while trying to move to vite and encountered a similar problem, importing from /dist/react didn't work, but when i use /dist/react/index it worked perfectly. Not sure if it was caused by me using vite or different tsconfig setup though.

**Comment by luwes** [comment] 2023-07-14 21:19
I'll have a look at this. I have a related issue where only `media-chrome/dist/react` would work in a Next.js example 
https://github.com/luwes/wesc/blob/0fcff3966262fe1d717dda008935b65d84883f90/examples/nextjs/components/player.js#L20-L20

**Comment by heff** [comment] 2023-07-24 22:30
@luwes can this issue be updated/closed?

**Comment by luwes** [comment] 2023-07-25 13:10
almost, the path import path issue should be fixed but the TS types not yet.

**Closed** 2023-07-25 14:21 UTC
Labels: bug
