### ISSUE TITLE
Avoid hiding controls on play button click

### ISSUE THREAD

**Issue by alessandroliveri** [muxinc/media-chrome#116] opened 2022-01-19 17:37 UTC
Q: Is it possible to avoid player controls hiding on click play button until the user cursor is over it?

This is what happens when I use the default `autohide`

https://user-images.githubusercontent.com/4834881/150183218-0b195507-04b3-49d4-a284-acd338da3f79.mov

This is what I'd like to do and I did dynamically setting autohide on video play/pause events

https://user-images.githubusercontent.com/4834881/150183282-2dd9d0ea-795f-4a91-87dc-c48352b43b20.mov

**Comment by cjpillsbury** [comment] 2022-01-19 19:02
Great feedback @alessandroliveri! I'm assuming you're ok with the current behavior for mobile/touch-based devices, and this is just an issue with desktop/cursor-based devices, correct?

**Comment by alessandroliveri** [comment] 2022-01-19 20:54
Hello @cjpillsbury, yes I'm talking about the desktop version: speaking of the mobile version, I'd prefer a time-based option and a tap on video area to make controls appear or a manual show/hide controls method so that I can manage them on my side because our users are not used tapping somewhere else on mobile to hide controls. 😃

**Comment by heff** [comment] 2022-01-22 23:28
@alessandroliveri can you check if this example is working as expected [here](https://unpkg.com/media-chrome@0.4.2/examples/basic.html)?

If I'm understanding this correctly it should already do what you're expecting, so I'm wondering if it's something about the control customization. If you can share an online example of your theme that would help.

**Comment by cjpillsbury** [comment] 2022-01-23 16:13
Good catch, @heff. @alessandroliveri, also make sure you're using the latest version.

**Comment by alessandroliveri** [comment] 2022-01-23 21:55
Hi @heff you are right with the basic elements the behavior is what I expect, I see the issue when I replace play and pause buttons with a custom svg: is there something that I have to add other than `slot="play"` and `slot="pause"`?

**Comment by luwes** [comment] 2022-04-15 21:35
@alessandroliveri any chance this is fixed in the mean time? 

I can't reproduce w/ custom SVG icons, see this example 
https://media-chrome.mux.dev/examples/themes/demuxed-2021-theme.html

**Comment by khushkaranbajwa** [comment] 2022-05-14 23:01
> Hello @cjpillsbury, thanks for your quick reply, yes I'm talking about the desktop version: speaking of the mobile version, I'd prefer a time-based option and a tap on video area to make controls appear or a manual show/hide controls method so that I can manage them on my side because our users are not used tapping somewhere else on mobile to hide controls. 😃

Is there any update on the mobile version changes suggested here? I'd be super interested in this especially if you have a centered play button to get the content playing.

**Comment by alessandroliveri** [comment] 2022-05-16 08:17
> @alessandroliveri any chance this is fixed in the mean time?
> 
> I can't reproduce w/ custom SVG icons, see this example https://media-chrome.mux.dev/examples/themes/demuxed-2021-theme.html

hi @luwes, I'm sorry for the late reply but I missed the notification 😅, now it seems to work as expected: thank you!

**Closed** 2022-07-15 16:49 UTC
Labels: bug
